sudo: true
dist: trusty
cache: false
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- openssl aes-256-cbc -K $encrypted_bc21448d0b37_key -iv $encrypted_bc21448d0b37_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- wget -qO- $URL | tar xJf -
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- ./sfdx/install
- export PATH=./sfdx/$(pwd):$PATH
- sfdx plugins:install salesforcedx@pre-release
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg
script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg -c -r human
- sfdx force:lightning:test:run -u ciorg
- sfdx force:org:delete -u ciorg -p
